### ISSUE TITLE
Performance issue for auto completion starting with C...

### ISSUE THREAD

**Issue by LudiusMaximus** [Grogir/LuaWoW#1]
When I type capital "C", Notepad++ becomes unresponsive for about 1 second before the drop-down menu with auto complete suggestions is shown. For all the other letters I tried, the menu appears instantly...

**Comment by Grogir** [comment]
There is really a lot of functions and tables starting with C, I dont really know what I could do without removing tables. A and G also cause a (shorter) delay.

**Comment by LudiusMaximus** [comment]
Hm, I see the problem. I think I then prefer the normal auto-completion of np++, which always suggests the words that I have used before in a file. These are mostly the only ones I need anyway. Thanks though!
