### ISSUE TITLE
No compatibility with new Notepad++

### ISSUE THREAD

**Issue by shikulja** [Grogir/LuaWoW#3]

**Comment by rdipardo** [comment]
@shikulja

<del>You can use this development build for now: https://github.com/rdipardo/LuaWoW/releases/tag/8.1.6-alpha</del>

**Edit:** The official release is here: https://github.com/Grogir/LuaWoW/releases

**Comment by shikulja** [comment]
@shikulja thanks

**Comment by rdipardo** [comment]
FYI, a new official version has been released: https://github.com/Grogir/LuaWoW/releases
